apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: public.ecr.aws/y6q8o0k2/nginx_image:latest
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
      - image: public.ecr.aws/y6q8o0k2/php_image:latest
        name: php
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
