apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: public.ecr.aws/y6q8o0k2/nginx_image:f153f075346402ba0ec248f572d96f6bf60fd313
        name: nginx
        ports:
        - containerPort: 80
      - image: public.ecr.aws/y6q8o0k2/php_image:f153f075346402ba0ec248f572d96f6bf60fd313
        name: php
        ports:
        - containerPort: 9000
      
